export const beerData = [
  {
    name: "プレミアムモルツ",
    maker: "suntory",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "金麦",
    maker: "suntory",
    type: "low-malt-beer",
    subType: "",
  },
  {
    name: "プレミアムモルツ 香るエール",
    maker: "suntory",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "プレミアムモルツ",
    maker: "suntory",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "クラシックラガー",
    maker: "kirin",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "一番搾り",
    maker: "kirin",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "一番搾り スタウト",
    maker: "kirin",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "クラシックラガー",
    maker: "kirin",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "アサヒ・ザ・マイスター",
    maker: "asahi",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "  アサヒドライプレミアム豊醸",
    maker: "asahi",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "  アサヒスーパードライ ドライブラック",
    maker: "asahi",
    type: "lager",
    subType: "schwarz",
  },
  {
    name: "  アサヒスーパードライ",
    maker: "asahi",
    type: "lager",
    subType: "pilsner",
  },

  {
    name: "香り華やぐエビス",
    maker: "sapporo",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "エビスビール",
    maker: "sapporo",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "シルクエビス",
    maker: "sapporo",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "エビスプレミアムブラック",
    maker: "sapporo",
    type: "lager",
    subType: "schwarz",
  },
  {
    name: "サッポロ生ビール 黒ラベル",
    maker: "sapporo",
    type: "lager",
    subType: "pilsner",
  },
  {
    name: "東京ブラック",
    maker: "yahobrewing",
    type: "ale",
    subType: "porter",
  },
  {
    name: "よなよなエール",
    maker: "yahobrewing",
    type: "ale",
    subType: "pale-ale",
  },
  {
    name: "水曜日のネコ",
    maker: "yahobrewing",
    type: "ale",
    subType: "white-ale",
  },
  {
    name: "インドの青鬼",
    maker: "yahobrewing",
    type: "ale",
    subType: "pale-ale",
  },
  {
    name: "Heineken",
    maker: "others",
    type: "lager",
    subType: "pailsner",
  },
  {
    name: "Guinness",
    maker: "others",
    type: "stout",
  },
];
