export const tsumamiData = [
  {
    name: "缶つま いか明太",
    maker: "suntory",
    taste: "hot",
    store: "all",
  },
  {
    name: "缶つまSmoke あさり",
    maker: "suntory",
    taste: "smokey",
    store: "all",
  },
  {
    name: "缶つま ほたて燻製油漬",
    maker: "suntory",
    taste: "umami",
    store: "all",
  },
  {
    name: "缶つま オイルサーディン",
    maker: "suntory",
    taste: "vinegary",
    store: "all",
  },
  {
    name: "(コリコリ旨い) いかそうめん",
    maker: "kirin",
    taste: "salty",
    store: "true",
  },
  {
    name: "(藻塩で味付けした)あたりめ",
    maker: "kirin",
    taste: "umami",
    store: "sevenEleven",
  },
  {
    name: "(やわらかい食感のイカの燻製) くんさき",
    maker: "kirin",
    taste: "umami",
    store: "sevenEleven",
  },
  {
    name: "(食べやすい食感の) 鮭とば",
    maker: "kirin",
    taste: "lager",
    store: "sevenEleven",
  },
  {
    name: "(するめの胴部分を使った) やわらかいいかフライ",
    maker: "asahi",
    taste: "umami",
    store: "sevenEleven",
  },
  {
    name: "(サクサク食感の) いかフライ旨辛味",
    maker: "asahi",
    taste: "hot",
    store: "sevenEleven",
  },
  {
    name: "(クリーミーでなめらなか食感の) チーズ鱈",
    maker: "asahi",
    taste: "creamy",
    store: "sevenEleven",
  },
  {
    name: "焼ほたて貝ひも 明太子味",
    maker: "asahi",
    taste: "hot",
    store: "all",
  },

  {
    name: "プリッと酢いか",
    maker: "sapporo",
    taste: "vinegary",
    store: "lawson",
  },
  {
    name: "エビスビール",
    maker: "sapporo",
    taste: "lager",
    store: "pailsner",
  },
  {
    name: "シルクエビス",
    maker: "sapporo",
    taste: "lager",
    store: "pailsner",
  },
  {
    name: "エビスプレミアムブラック",
    maker: "sapporo",
    taste: "lager",
    store: "pailsner",
  },
  {
    name: "サッポロ生ビール 黒ラベル",
    maker: "sapporo",
    taste: "lager",
    store: "pailsner",
  },
  {
    name: "東京ブラック",
    maker: "yahobrewing",
    taste: "ale",
    store: "pailsner",
  },
  {
    name: "よなよなエール",
    maker: "yahobrewing",
    taste: "ale",
    store: "pailsner",
  },
  {
    name: "水曜日のネコ",
    maker: "yahobrewing",
    taste: "ale",
    store: "pailsner",
  },
  {
    name: "インドの青鬼",
    maker: "yahobrewing",
    taste: "ale",
    store: "pailsner",
  },
  {
    name: "Heineken",
    maker: "others",
    taste: "lager",
    store: "pailsner",
  },
  {
    name: "Guinness",
    maker: "others",
    store: "pailsner",
  },
];
